server:
  tomcat:
    uri-encoding: UTF-8
  port: 18080

spring:
  http:
    encoding:
      force: true
      charset: UTF-8
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: create-drop
      naming:
        strategy: org.hibernate.cfg.EJB3NamingStrategy
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true
    properties:
        hibernate.format_sql: true
  h2:
    console:
      enabled: true
      #settings:
      #  trace: true
  datasource:
    url: jdbc:h2:~/db_h2/develop

logging:
  level: debug